app_graph3d_src = $(addprefix apps/graph3d/,\
  app.cpp \
)

app_graph3d_src += $(app_graph3d_test_src)
SOURCES_apps += $(app_graph3d_src)

$(eval $(call depends_on_image,apps/graph3d/app.cpp,apps/graph3d/graph3d_icon.png))
